trigger:
- main

pool:
  name: 'sh-tf-agent-pool'

stages:
- stage: deploy
  jobs:
  - job: deploy
    steps:

    - checkout: self

    - task: terraformInstaller@0
      inputs:
        terraformVersion: '1.14.3'

    - script: |
        terraform init
      displayName: 'Terraform Init'

    - script: |
        terraform plan
      displayName: 'Terraform Plan'

    - script: |
        terraform apply
      displayName: 'Terraform Apply'