trigger:
- main

pool:
  name: 'sh-tf-agent-pool'

stages:
- stage: deploy
  jobs:
  - job: deploy
    steps:

    - checkout: self

    - script: |
        pwd
        ls -al
      displayName: 'Show workspace'

    - script: |
        sudo apt-get update
        sudo apt-get install -y unzip
      displayName: 'Install Unzip'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      displayName: 'Terraform Task'
      inputs:
        terraformVersion: '1.14.3'

    - script: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      displayName: 'Install Azure CLI'

    - task: AzureCLI@2
      displayName: 'Login to Azure and run Terraform'
      inputs:
        azureSubscription: 'bicep-deployment-test-access'
        scriptType: bash
        scriptLocation: inlineScript
      inlineScript: |
        terraform init
        terraform plan
        terraform apply -auto-approve
